# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  issues:
    types: [opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Create Project Card
        # You may pin to the exact commit or the version.
        # uses: peter-evans/create-or-update-project-card@c75ba6ac3c7c432dedd22a553951c216a4664b5f
        uses: peter-evans/create-or-update-project-card@v1.1.4
        with:
          # GitHub auth token
          token: ${{ github.token }}
          # The location of the project. Either a repository, organization, or user.
          project-location: ${{ github.repository }}
          # The number of the project. Semi-required. Either `project-number` OR `project-name` must be supplied.
          project-number: 1
          # The name of the project. Semi-required. Either `project-number` OR `project-name` must be supplied. Note that a project's name is not unique. The action will use the first matching project found.
          column-name: TODO
          # The GitHub repository containing the issue or pull request.
          repository: ${{ github.repository }}
          # The issue or pull request number to associate with the card.
          issue-number: ${{ github.event.issue.number }}
